AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.0
  Exclude:
    - bin/*
    - vendor/bundle/**/*

Layout:
  Metrics/LineLength:
    Max: 110

  Metrics/AbcSize:
    Enabled: false

  Metrics/ClassLength:
    Exclude:
      - lib/distribusion/route.rb
      - test/**/*_test.rb
