AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  Exclude:
    - bin/*
    - vendor/bundle/**/*

Metrics/LineLength:
  Max: 110

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - lib/distribusion/route.rb
    - test/**/*_test.rb
