version: 2
jobs:
  golang:
    docker:
      - image: circleci/golang:1.9.2
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run: go get -u github.com/jstemmer/go-junit-report
      - run: go get -v -t -d ./...
      - run: go test ./... -v 2>&1 | go-junit-report > $TEST_RESULTS/report.xml
      - store_test_results:
          path: /tmp/test-results
  distribusion:
    working_directory: ~/samples/distribusion
    docker:
      - image: circleci/ruby:2.6.0-preview2
        environment:
          RUBYOPT: "--enable-frozen-string-literal"
    steps:
      - checkout:
          path: ~/samples
      - restore_cache:
          key: dependency-cache-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: dependency-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: bundle exec rubocop -c .rubocop.yml
      - run: bundle exec rake test
      - run: bundle exec ruby --enable-frozen-string-literal ./bin/local -v -s all -p $DISTRIBUSION_PASSPHRASE | sed s/"${DISTRIBUSION_PASSPHRASE}"/xxx/g

      - store_artifacts:
          path: coverage

workflows:
  version: 2
  distribusion:
    jobs:
      - distribusion
      - golang
