version: 2
dry:
  restore_shards_cache: &restore_shards_cache
    # Use {{ checksum "shard.yml" }} if developing a shard instead of an app
    keys:
      - shards-cache-v26-{{ .Branch }}-{{ checksum "shard.lock" }}
      - shards-cache-v26-{{ .Branch }}
      - shards-cache-v26

  save_shards_cache: &save_shards_cache
    # Use {{ checksum "shard.yml" }} if developing a shard instead of an app
    key: shards-cache-v1-{{ .Branch }}-{{ checksum "shard.lock" }}
    paths:
      - ./shards-cache

jobs:
  golang:
    working_directory: /go/src/github.com/miry/samples/
    docker:
      - image: circleci/golang:1.11.1
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS/{algorithms,btree,codinggame,gohttproxy,justforfunc}
      - run: go get -u github.com/jstemmer/go-junit-report
      - run: go get -v -t -d ./...
      - run: go test ./algorithms/... -v |& go-junit-report > $TEST_RESULTS/algorithms/report.xml
      - run: go test ./codinggame/... -v |& go-junit-report > $TEST_RESULTS/codinggame/report.xml
      - run: go test ./gohttproxy/... -v |& go-junit-report > $TEST_RESULTS/gohttproxy/report.xml
      - run: go test ./justforfunc/... -v |& go-junit-report > $TEST_RESULTS/justforfunc/report.xml
      - run: go test -bench=. ./benchmarks/... -v
      - store_test_results:
          path: /tmp/test-results
  ruby:
    docker:
      - image: circleci/ruby:2.6.0-preview2
    steps:
      - checkout
      - run: ruby -I. -I./codewars  codewars/sudoku_test.rb
  crystal:
    # https://crystal-lang.org/2018/09/04/using-circleci-2.0-for-your-crystal-projects.html
    docker:
      - image: crystallang/crystal:0.26.1
    steps:
      - run: crystal --version
      - checkout
      - restore_cache: *restore_shards_cache
      - run: shards install
      - save_cache: *save_shards_cache
      - run: crystal run algorithms/list/node_test.cr -- --verbose
  distribusion:
    working_directory: ~/samples/distribusion
    docker:
      - image: circleci/ruby:2.6.0-preview2
        environment:
          RUBYOPT: "--enable-frozen-string-literal"
    steps:
      - checkout:
          path: ~/samples
      - restore_cache:
          key: dependency-cache-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: dependency-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: bundle exec rubocop -c .rubocop.yml
      - run: bundle exec rake test
      - run: bundle exec ruby --enable-frozen-string-literal ./bin/local -v -s all -p $DISTRIBUSION_PASSPHRASE | sed s/"${DISTRIBUSION_PASSPHRASE}"/xxx/g

      - store_artifacts:
          path: coverage

workflows:
  version: 2
  distribusion:
    jobs:
      - distribusion
  tests:
    jobs:
      - golang
      - ruby
      - crystal
