receivers:
  # Make sure to add the otlp receiver.
  # This will open up the receiver on port 55680
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:30080"
processors:
extensions:
  health_check: {}
  pprof: {}

exporters:
  jaeger:
    endpoint: "jaeger-collector.observability.svc.cluster.local:14250"
    insecure: true
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: "default"
  logging:
    loglevel: debug
service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [jaeger]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheus, logging]
